spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservice-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    #druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 5
    #最大连接等待超时时间
    maxWait: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.szm.microservice.entity

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: provider-dept-8001-dev

info:
  app.name: szm-microservicecloud
  company.name: szm
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
  server:
    port: 8001
  spring:
    profiles: test
    application:
      name: microservice-dept
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring-cloud-test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
      #druid连接池
      type: com.alibaba.druid.pool.DruidDataSource
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 5
      #最大连接等待超时时间
      maxWait: 60000
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: cn.szm.microservice.entity

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    instance:
      prefer-ip-address: true
      instance-id: provider-dept-8001-test

  info:
    app.name: szm-microservicecloud
    company.name: szm
    build.artifactId: $project.artifactId$
    build.version: $project.version$

